language: elixir
sudo: false

branches:
  only:
    - master
    - development

elixir:
  - 1.10.4
  - 1.11.2
otp_release:
  - 21.0
  - 22.2.8
  - 23.1.2

matrix:
  include:
    - elixir: 1.10.0
      otp_release: 21.0
    - elixir: 1.10.0
      otp_release: 22.0
    - elixir: 1.11.0
      otp_release: 22.0
    - elixir: 1.11.1
      otp_release: 23.0.1
